# Theme code

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Roderick Dev
tagline:          'Putting my technical and social system thoughts out to the world.'
description:      'Thoughts, learnings, and findings from a social scientist embedded in the tech world'
url:              http://www.roderick.dev
baseurl:          /

author:
  name:           'Tom Roderick'
  url:            https://twitter.com/tom_roderick

paginate:         5

# Custom vars
github:
  repo:           https://github.com/tomrod/roderickdev
